version: '3.1'

services:

  postgre:
    container_name: 'todo_db'
    image: postgres:13.5-alpine3.15
    restart: always
    ports:
    - '3234:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notepad
    volumes:
      - postgre:/var/db/postgre/data
    networks:
      - notepad



volumes:
  postgre:

networks:
  notepad:
    driver: bridge