spring:
  datasource:
    url: jdbc:postgresql://localhost:3234/notepad
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    generate-ddl: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml