DROP TABLE IF EXISTS role;
DROP SEQUENCE IF EXISTS role_seq;

CREATE SEQUENCE role_seq START WITH 100000;

CREATE TABLE role (
    id BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('role_seq'),
    name VARCHAR(128) NOT NULL UNIQUE
);