DROP TABLE IF EXISTS tag;
DROP SEQUENCE IF EXISTS tag_seq;

CREATE SEQUENCE tag_seq START WITH 1;

CREATE TABLE tag(
    id BIGINT PRIMARY KEY NOT NULL DEFAULT nextval('tag_seq'),
    tag_name VARCHAR NOT NULL
);